##############################################################
# redmine maintenance
##############################################################
- name: create workdir
  file:
    path: "/tmp/redmine-{{ inventory_hostname }}"
    state: directory
    mode: 0755

- name: upload shell script
  template:
    src: "upd_redmine.sh.j2"
    dest: "/tmp/redmine-{{ inventory_hostname }}/upd_redmine.sh"
    mode: 0755

- name: execute shell script
  shell: /tmp/redmine-{{ inventory_hostname }}/upd_redmine.sh
  register: out_from_shell
  notify: restart service

- name: output stdout
  debug:
    var: out_from_shell.stdout_lines
  when: debug_stdout

- name: output stderr
  debug:
    var: out_from_shell.stderr_lines
  when: debug_stderr

- name: delete workdir
  file:
    path: "/tmp/redmine-{{ inventory_hostname }}"
    state: absent
